name: demo_widgets
description: A new Flutter project.
version: 0.2.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/yohom/demo_widgets

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  decorated_flutter: ^0.24.3+1
  flutter_syntax_view: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter